- name: Pegando os outputs da Stack
  local_action: cloudformation_facts
                stack_name="baseInfra"
  register: stack

- name: "Logando no Repo"
  raw: aws ecr get-login-password --region {{ region }} | docker login --username AWS --password-stdin {{ stack.ansible_facts.cloudformation.baseInfra.stack_outputs.RepoURI }}

- name: "Buildando Back-End"
  raw:  docker build -t backapp ../back/

- name: "Tag local back-end image para o Repo Remoto"
  raw: docker tag backapp:latest {{ stack.ansible_facts.cloudformation.baseInfra.stack_outputs.BackRepo }}

- name: "Dando push na imagem back-end"
  raw: docker push {{ stack.ansible_facts.cloudformation.baseInfra.stack_outputs.BackRepo }}

- name: "Buildando Front-End"
  raw: docker build -t frontapp ../front/

- name: "Tag local front-end image para o Repo Remoto"
  raw: docker tag frontapp:latest {{ stack.ansible_facts.cloudformation.baseInfra.stack_outputs.FrontRepo }}

- name: "Dando push na imagem front-end"
  raw: docker push {{ stack.ansible_facts.cloudformation.baseInfra.stack_outputs.FrontRepo }}