Description:  Template to provide Task Definitions and the Services 

Parameters:
  Command:
   Type: String
   Description: The command to put inside command task

Resources:

# Task Definition Front-End
  TaskDefinitionCommand:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "TaskCommand"
      ContainerDefinitions:
      - Name: runcommand
        Command: !Ref Command
        Cpu: '10'
        Essential: 'true'
        Image: "mysql:latest"
        Memory: '128'
        MountPoints:
        - ContainerPath: /usr/app
          SourceVolume: my-vol
        PortMappings:
        - ContainerPort: 3306
      Volumes:
      - Name: my-vol

# Service Front-End
  serviceCommand:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !ImportValue "baseInfra-ECSClusterFrontEnd"
      DesiredCount: '1'
      LaunchType: "EC2"
      LoadBalancers:
      Role: !Ref 'ECSServiceRole'
      TaskDefinition: !Ref TaskDefinitionCommand

# IAM Roles
  ECSServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [ecs.amazonaws.com]
          Action: ['sts:AssumeRole']
      Path: /
      Policies:
      - PolicyName: ecs-service
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action: ['elasticloadbalancing:DeregisterInstancesFromLoadBalancer', 'elasticloadbalancing:DeregisterTargets',
              'elasticloadbalancing:Describe*', 'elasticloadbalancing:RegisterInstancesWithLoadBalancer',
              'elasticloadbalancing:RegisterTargets', 'ec2:Describe*', 'ec2:AuthorizeSecurityGroupIngress']
            Resource: '*'