- name: "Criando infraestrutura (VPC,Subnets, SGs, RDS, ELB, AutoScaling, ECS, IAMs, ECR )"
  raw: aws cloudformation create-stack \
         --stack-name baseInfra \
         --template-body file://../CloudFormation/create_infra.yaml \
         --parameters ParameterKey=KeyPair,ParameterValue={{ KeyPair }} \
           ParameterKey=region,ParameterValue={{ region }} \
           ParameterKey=zone1,ParameterValue={{ zone1 }} \
           ParameterKey=zone2,ParameterValue={{ zone2 }} \
           ParameterKey=AMI,ParameterValue={{ AMI }} \
           ParameterKey=instanceType,ParameterValue={{ instanceType }} \
           ParameterKey=masterUserName,ParameterValue={{ masterUserName }} \
           ParameterKey=masterUserPassword,ParameterValue={{ masterUserPassword }} \
           ParameterKey=maxScalingSize,ParameterValue={{ maxScalingSize }} \
           ParameterKey=minScalingSize,ParameterValue={{ minScalingSize }} \
         --capabilities CAPABILITY_IAM

- name: Esperando a Stack ficar pronta
  raw: aws cloudformation wait stack-create-complete --stack-name baseInfra

- name: Pegando a URL do LoadBalancer da Stack
  local_action: cloudformation_facts
                stack_name="baseInfra"
  register: stackName

- name: Criando o Banco de Dados e a Tabela 
  raw: mysql -u {{ masterUserName }} -p{{masterUserPassword}} -h ${DatabaseURL} \
       -e "create database preferences;use preferences;create table if not exists preferences (id int auto_increment primary key, ip varchar(20), preference varchar(10));"
  