- name: Atualizando repo
  raw: apt update

- name: "Instalando Python3 e Pip3 na máquina local"
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3
      - python3-pip

- name: "Criando infraestrutura (VPC,Subnets, SGs, RDS, ELB, AutoScaling, ECS, IAMs, ECR )"
  raw: aws cloudformation create-stack \
         --stack-name baseInfra \
         --template-body file://../CloudFormation/create_infra.yaml \
         --parameters ParameterKey=KeyPair,ParameterValue={{ KeyPair }} \
           ParameterKey=region,ParameterValue={{ region }} \
           ParameterKey=zone1,ParameterValue={{ zone1 }} \
           ParameterKey=zone2,ParameterValue={{ zone2 }} \
           ParameterKey=AMI,ParameterValue={{ AMI }} \
           ParameterKey=instanceType,ParameterValue={{ instanceType }} \
           ParameterKey=masterUserName,ParameterValue={{ masterUserName }} \
           ParameterKey=masterUserPassword,ParameterValue={{ masterUserPassword }} \
           ParameterKey=maxScalingSize,ParameterValue={{ maxScalingSize }} \
           ParameterKey=minScalingSize,ParameterValue={{ minScalingSize }} \
         --capabilities CAPABILITY_IAM


- name: "Instalando boto3"
  raw: pip3 install boto3

- name: "Instalando python3 mysqldb"
  apt:
    name: python3-mysqldb

- name: Esperando a Stack ficar pronta
  raw: aws cloudformation wait stack-create-complete --stack-name baseInfra

- name: Pegando os outputs da Stack
  local_action: cloudformation_facts
                stack_name="baseInfra"
  register: stack

- name: Instalando o DB e a Tabela no MySql
  mysql_db: name=preferences
            login_host={{ stack.RdsURL }} 
            login_password={{ masterUserPassword }}
            login_user={{ masterUserName }}
            login_port=3306
            state=import
            target=../mysql/seed.sql
