- name: "Criando infraestrutura (VPC,Subnets, SGs, RDS, ELB, AutoScaling, ECS, IAMs, ECR )"
  raw: aws cloudformation create-stack \
         --stack-name baseInfra \
         --template-body file://../CloudFormation/create_infra.yaml \
         --parameters ParameterKey=KeyPair,ParameterValue={{ KeyPair }} \
           ParameterKey=region,ParameterValue={{ region }} \
           ParameterKey=zone1,ParameterValue={{ zone1 }} \
           ParameterKey=zone2,ParameterValue={{ zone2 }} \
           ParameterKey=AMI,ParameterValue={{ AMI }} \
           ParameterKey=instanceType,ParameterValue={{ instanceType }} \
           ParameterKey=masterUserName,ParameterValue={{ masterUserName }} \
           ParameterKey=masterUserPassword,ParameterValue={{ masterUserPassword }} \
           ParameterKey=maxScalingSize,ParameterValue={{ maxScalingSize }} \
           ParameterKey=minScalingSize,ParameterValue={{ minScalingSize }} \
         --capabilities CAPABILITY_IAM

- name: Atualizando repo
  raw: apt update

- name: "Instalando Pip3 se não existir na máquina local"
  apt:
    name: "python3-pip"

- name: "Instalando boto3"
  raw: pip3 install boto3

- name: "Instalando o Docker"
  apt:
    name: "docker"

- name: Esperando a Stack ficar pronta
  raw: aws cloudformation wait stack-create-complete --stack-name baseInfra

- name: Pegando os outputs da Stack
  local_action: cloudformation_facts
                stack_name="baseInfra"
  register: stack

- name: "Adicionando a variáveis de ambiente no app back-end"
  raw: echo "SERVICE_PORT=3333\nMYSQL_HOST={{ stack.ansible_facts.cloudformation.baseInfra.stack_outputs.RdsURL }}\nMYSQL_USER={{ masterUserName }}\nMYSQL_PASSWORD={{ masterUserPassword }}\nMYSQL_DB=preferences" > "../back/.env" 

- name: "Adicionando a variáveis de ambiente no app back-end"
  raw: echo "SERVICE_PORT=80\nBACKEND_HOST={{ stack.ansible_facts.cloudformation.baseInfra.stack_outputs.LoadBalancerUrlBack }}\nBACKEND_PORT=3333" > "../front/.env"

- name: "Pegando os ids das instâncias do Back-End"
  raw: aws ec2 describe-instances --filters Name=tag:Name,Values=BackEndApp Name=instance-state-name,Values=running \
      --output text --query 'Reservations[*].Instances[*].InstanceId'
  register: ids

- name: "Instalando o mysql em uma instância de back-end"
  raw:  aws ssm send-command \
        --instance-ids "{{ ids.stdout_lines[0] }}" \
        --document-name "AWS-RunShellScript" \
        --parameters commands="yum update && yum install -y mysql"

- name: "Rodando Script na instância back-end para criar o DB e a Table"
  raw: aws ssm send-command \
        --instance-ids "{{ ids.stdout_lines[0] }}" \
        --document-name "AWS-RunShellScript" \
        --parameters commands='mysql -u {{ masterUserName }} -p{{ masterUserPassword }} -h {{ stack.ansible_facts.cloudformation.baseInfra.stack_outputs.RdsURL }} -e "create database preferences; use preferences; create table preferences (id INT AUTO_INCREMENT PRIMARY KEY, ip VARCHAR(20), preference VARCHAR(10));"'
